#!/bin/bash
help_text="
NAME
   gen_ora_web_pgs - Creates web pages for Oracle scripts

USAGE
   gen_ora_web_pgs

DESCRIPTION
   Creates web pages for Oracle scripts.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Creates web pages for Oracle scripts"
desc_line="Creates web pages for Oracle scripts"

rm -f /c/MJN/github/mjnurse-github-io/ORacle-R/Script*

cd /c/MJN/github/oracle

for f in $(grep -l "^-- desc_line" *.sql); do

   dl="$(grep '^-- desc_line' $f | sed 's/-- desc_line: *//; s/ *$//')"
   dest=$(echo "/c/MJN/github/mjnurse-github-io/ORacle-R/Script $f - $dl.md" | sed "s/ /_/g")

   echo "---" > $dest
   echo "title: $f - $dl" >> $dest
   echo "---" >> $dest
   echo "" >> $dest
   echo "\`\`\`sql" >> $dest
   cat $f >> $dest
   echo "\`\`\`" >> $dest

   echo $dest
done

