#!/bin/bash
help_text="
NAME
  gen-bash-readme - Create a README.md for the bash scripts repo.

USAGE
  gen-bash-readme

DESCRIPTION
  Create a README.md for the bash scripts repo.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Create a README.md for the bash scripts repo"

rme="/c/MJN/github/bash/README.md"

echo "# Bash Scripts" > $rme
echo "" >> $rme

for f in $(grep -l -e "desc_line=" *); do
   cat $f | sed -n '/^desc_line=/p;' | sed 's/desc_line=//; s/"//g' \
      | sed "s/^/- [**$f**](https:\/\/github.com\/mjnurse\/bash\/blob\/master\/$f) - /" >> $rme
   echo "" >> $rme
done
