#!/bin/bash
help_text="
NAME
  gen-ora-readme - One line description.

USAGE
  gen-ora-readme [options] <parameters>

OPTIONS
  -x
    Description...

  -h|--help
    Show help text.

DESCRIPTION
  Description description description description.

AUTHOR
  mjnurse.dev - 2020
"
help_line="tbc"

dir="/c/MJN/github/oracle"
rme="$dir/README.md"

echo "# Oracle Scripts" > $rme
echo "" >> $rme

cd $dir
for f in $(grep -l -e "-- *desc_line:" * ); do
   cat $f | sed -n '/^-- *desc_line:/p;' | sed 's/-- *desc_line: *//; s/"//g' \
       | sed "s/^/- [**$f**](https:\/\/github.com\/mjnurse\/oracle\/blob\/master\/$f) - /" >> $rme
   echo "" >> $rme
done
