#!/bin/bash
help_text="
NAME
   gvim - Runs windows gvim and fixes files paths

USAGE
   gvim <filename(s)>

DESCRIPTION
   Runs windows gvim and fixes files paths.

AUTHOR
  mjnurse.uk 2020
"
help_line="Runs windows gvim and fixes file paths"
desc_line="Runs windows gvim and fixes file paths"

files="$*"
fixed_files="$(echo $files | sed 's/\/c\//C:\//g')"
gvim.exe $fixed_files &
