#!/bin/bash
help_text="
NAME
   note - Creates a new note article

USAGE
   note <title: spaces allowed>

DESCRIPTION
   A basic script to create a new note article.
"

help_line="Creates a Note article: note <title: spaces allowed>"

if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ]; then
   echo "$help_text"
   exit
fi

params=$*

filename=Notes.${params// /_}.article
echo $filename

read -p "Create [yN]: " yn

if [ "${yn^}" == "Y" ]; then
   echo "# ${params}" > /c/MJN/gdrive/web/content-mjnurse-uk/Notes.articles/$filename
   cd /c/MJN/gdrive/web/content-mjnurse-uk/Notes.articles
   gvim $filename
   cd /c/MJN/gdrive/web/content-mjnurse-uk/Notes.articles
   ls
fi
