#!/bin/bash
help_text="
NAME
   pu - One line description.

USAGE
   pu [options] <parameters>

OPTIONS
   -x
      Description...

   -h|--help
      Show help text.

DESCRIPTION
   Description description description description.

AUTHOR
  mjnurse.dev - 2020
"
help_line="tbc"

git add .
git status

if [[ "$1" != "-f" ]]; then
  read -p 'Press a key to continue'
fi

git commit -m 'Various'
git push origin master
